spring:
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/workerdb
    username: worker
    password: worker
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update