server:
  port: 8082

spring:
  application:
    name: tax-api
  mvc:
    path match:
      matching-strategy: ANT_PATH_MATCHER

  # Liquibase
  spring:
    liquibase:
      change-log: classpath:db/changelog/db.changelog-master.yaml
      user: worker
      password: worker

  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/workerdb
    username: worker
    password: worker
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka/
